AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Exported by architect/package@8.4.1 on 2023-04-12T22:36:25.703Z
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: ArcGlobalPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            Resource: arn:aws:logs:*:*:*
      - PolicyName: ArcStaticBucketPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:DeleteObject
            - s3:ListBucket
            Resource:
            - Fn::Sub:
              - arn:aws:s3:::${bukkit}
              - bukkit:
                  Ref: StaticBucket
            - Fn::Sub:
              - arn:aws:s3:::${bukkit}/*
              - bukkit:
                  Ref: StaticBucket
      - PolicyName: ArcSimpleNotificationServicePolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - sns:Publish
            Resource:
              Fn::Sub:
              - arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${AWS::StackName}*
              - {}
  PostbillEventTopicParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name:
        Fn::Sub:
        - /${AWS::StackName}/events/${event}
        - event: postbill
      Value:
        Ref: PostbillEventTopic
  TweetbillEventTopicParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name:
        Fn::Sub:
        - /${AWS::StackName}/events/${event}
        - event: tweetbill
      Value:
        Ref: TweetbillEventTopic
  StaticBucketParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name:
        Fn::Sub:
        - /${AWS::StackName}/static/${key}
        - key: bucket
      Value:
        Ref: StaticBucket
  StaticFingerprintParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name:
        Fn::Sub:
        - /${AWS::StackName}/static/${key}
        - key: fingerprint
      Value: 'false'
  ParameterStorePolicy:
    Type: AWS::IAM::Policy
    DependsOn: Role
    Properties:
      PolicyName: ArcParameterStorePolicy
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action:
          - ssm:GetParametersByPath
          - ssm:GetParameter
          Resource:
            Fn::Sub:
            - arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AWS::StackName}
            - {}
        - Effect: Allow
          Action:
          - ssm:GetParametersByPath
          - ssm:GetParameter
          Resource:
            Fn::Sub:
            - arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AWS::StackName}/*
            - {}
        - Effect: Allow
          Action:
          - ssm:GetParametersByPath
          - ssm:GetParameter
          Resource:
            Fn::Sub:
            - arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AWS::StackName}/*/*
            - {}
      Roles:
      - Ref: Role
  HTTP:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      DefinitionBody:
        openapi: 3.0.1
        info:
          title:
            Ref: AWS::StackName
        paths:
          /:
            get:
              x-amazon-apigateway-integration:
                payloadFormatVersion: '2.0'
                type: aws_proxy
                httpMethod: POST
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetIndexHTTPLambda.Arn}/invocations
                connectionType: INTERNET
          /_static/{proxy+}:
            get:
              x-amazon-apigateway-integration:
                payloadFormatVersion: '1.0'
                type: http_proxy
                httpMethod: GET
                uri:
                  Fn::Sub:
                  - https://${bukkit}.s3.${AWS::Region}.amazonaws.com/{proxy}
                  - bukkit:
                      Ref: StaticBucket
                connectionType: INTERNET
                timeoutInMillis: 30000
  GetIndexHTTPLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: s3://billbot3-cfn-deployments-5fc23/ad75d6e28ca4624f14260be74ba3adcc
      Runtime: nodejs18.x
      Architectures:
      - arm64
      MemorySize: 1152
      EphemeralStorage:
        Size: 512
      Timeout: 5
      Environment:
        Variables:
          ARC_APP_NAME: billbot3
          ARC_ENV: staging
          ARC_ROLE:
            Ref: Role
          ARC_SESSION_TABLE_NAME: jwe
          ARC_STACK_NAME:
            Ref: AWS::StackName
          ARC_STATIC_BUCKET:
            Ref: StaticBucket
          ARC_STATIC_SPA: false
          ACCESS_TOKEN: 3H0YWldYQ7z--R2NPdA16GqK_AtlZ6Vn1gCvXs7Wg5U
          CLIENT_KEY: m--6ewT3v3E6N2M_1LzTgXXOhzLhXxpbVRdvh7wyFGQ
          CLIENT_SECRET: gCQd_XqWmcBzNVH2EfJZRY9C9jQrXWxFBxXbTB5Qonw
          TWITTER_ACCESS_TOKEN: 1572763815351128064-6xUKr4T25fDS6lCJ5nqohHNbumQ2Vy
          TWITTER_ACCESS_TOKEN_SECRET: 7aSFpxyIE7NzGPH5F6bzn4ylX4g9SZLKVZ9i2fgYi5GZs
          TWITTER_API_KEY: jbT0eEP0DHtv2VxiVE3ezCMSE
          TWITTER_API_SECRET: R20LZBrEysCk6BQ8nwquMcrYLLc0dZUu9QYWhmy7ZsaBCMi2AH
      Role:
        Fn::Sub:
        - arn:aws:iam::${AWS::AccountId}:role/${roleName}
        - roleName:
            Ref: Role
      Events:
        GetIndexHTTPEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
            ApiId:
              Ref: HTTP
    ArcMetadata:
      pragma: http
      name: get /
      method: get
      path: /
  PostbillEventLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: s3://billbot3-cfn-deployments-5fc23/e532068147495447ebf3044c7d514f24
      Runtime: nodejs18.x
      Architectures:
      - arm64
      MemorySize: 1152
      EphemeralStorage:
        Size: 512
      Timeout: 5
      Environment:
        Variables:
          ARC_APP_NAME: billbot3
          ARC_ENV: staging
          ARC_ROLE:
            Ref: Role
          ARC_SESSION_TABLE_NAME: jwe
          ARC_STACK_NAME:
            Ref: AWS::StackName
          ARC_STATIC_BUCKET:
            Ref: StaticBucket
          ACCESS_TOKEN: 3H0YWldYQ7z--R2NPdA16GqK_AtlZ6Vn1gCvXs7Wg5U
          CLIENT_KEY: m--6ewT3v3E6N2M_1LzTgXXOhzLhXxpbVRdvh7wyFGQ
          CLIENT_SECRET: gCQd_XqWmcBzNVH2EfJZRY9C9jQrXWxFBxXbTB5Qonw
          TWITTER_ACCESS_TOKEN: 1572763815351128064-6xUKr4T25fDS6lCJ5nqohHNbumQ2Vy
          TWITTER_ACCESS_TOKEN_SECRET: 7aSFpxyIE7NzGPH5F6bzn4ylX4g9SZLKVZ9i2fgYi5GZs
          TWITTER_API_KEY: jbT0eEP0DHtv2VxiVE3ezCMSE
          TWITTER_API_SECRET: R20LZBrEysCk6BQ8nwquMcrYLLc0dZUu9QYWhmy7ZsaBCMi2AH
      Role:
        Fn::Sub:
        - arn:aws:iam::${AWS::AccountId}:role/${roleName}
        - roleName:
            Ref: Role
      Events:
        PostbillEvent:
          Type: SNS
          Properties:
            Topic:
              Ref: PostbillEventTopic
    ArcMetadata:
      pragma: events
      name: postbill
  PostbillEventTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Postbill
      Subscription: []
  TweetbillEventLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: s3://billbot3-cfn-deployments-5fc23/eb7a14f718b01d684d6faba12a8a5969
      Runtime: nodejs18.x
      Architectures:
      - arm64
      MemorySize: 1152
      EphemeralStorage:
        Size: 512
      Timeout: 5
      Environment:
        Variables:
          ARC_APP_NAME: billbot3
          ARC_ENV: staging
          ARC_ROLE:
            Ref: Role
          ARC_SESSION_TABLE_NAME: jwe
          ARC_STACK_NAME:
            Ref: AWS::StackName
          ARC_STATIC_BUCKET:
            Ref: StaticBucket
          ACCESS_TOKEN: 3H0YWldYQ7z--R2NPdA16GqK_AtlZ6Vn1gCvXs7Wg5U
          CLIENT_KEY: m--6ewT3v3E6N2M_1LzTgXXOhzLhXxpbVRdvh7wyFGQ
          CLIENT_SECRET: gCQd_XqWmcBzNVH2EfJZRY9C9jQrXWxFBxXbTB5Qonw
          TWITTER_ACCESS_TOKEN: 1572763815351128064-6xUKr4T25fDS6lCJ5nqohHNbumQ2Vy
          TWITTER_ACCESS_TOKEN_SECRET: 7aSFpxyIE7NzGPH5F6bzn4ylX4g9SZLKVZ9i2fgYi5GZs
          TWITTER_API_KEY: jbT0eEP0DHtv2VxiVE3ezCMSE
          TWITTER_API_SECRET: R20LZBrEysCk6BQ8nwquMcrYLLc0dZUu9QYWhmy7ZsaBCMi2AH
      Role:
        Fn::Sub:
        - arn:aws:iam::${AWS::AccountId}:role/${roleName}
        - roleName:
            Ref: Role
      Events:
        TweetbillEvent:
          Type: SNS
          Properties:
            Topic:
              Ref: TweetbillEventTopic
    ArcMetadata:
      pragma: events
      name: tweetbill
  TweetbillEventTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Tweetbill
      Subscription: []
  CheckbillsScheduledLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: s3://billbot3-cfn-deployments-5fc23/c6cecbb6eb4811255dbf35db8c9933a3
      Runtime: nodejs18.x
      Architectures:
      - arm64
      MemorySize: 1152
      EphemeralStorage:
        Size: 512
      Timeout: 5
      Environment:
        Variables:
          ARC_APP_NAME: billbot3
          ARC_ENV: staging
          ARC_ROLE:
            Ref: Role
          ARC_SESSION_TABLE_NAME: jwe
          ARC_STACK_NAME:
            Ref: AWS::StackName
          ARC_STATIC_BUCKET:
            Ref: StaticBucket
          ACCESS_TOKEN: 3H0YWldYQ7z--R2NPdA16GqK_AtlZ6Vn1gCvXs7Wg5U
          CLIENT_KEY: m--6ewT3v3E6N2M_1LzTgXXOhzLhXxpbVRdvh7wyFGQ
          CLIENT_SECRET: gCQd_XqWmcBzNVH2EfJZRY9C9jQrXWxFBxXbTB5Qonw
          TWITTER_ACCESS_TOKEN: 1572763815351128064-6xUKr4T25fDS6lCJ5nqohHNbumQ2Vy
          TWITTER_ACCESS_TOKEN_SECRET: 7aSFpxyIE7NzGPH5F6bzn4ylX4g9SZLKVZ9i2fgYi5GZs
          TWITTER_API_KEY: jbT0eEP0DHtv2VxiVE3ezCMSE
          TWITTER_API_SECRET: R20LZBrEysCk6BQ8nwquMcrYLLc0dZUu9QYWhmy7ZsaBCMi2AH
      Role:
        Fn::Sub:
        - arn:aws:iam::${AWS::AccountId}:role/${roleName}
        - roleName:
            Ref: Role
      Events: {}
    ArcMetadata:
      pragma: scheduled
      name: checkbills
  CheckbillsScheduledEvent:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 11 ? * * *)
      Targets:
      - Arn:
          Fn::GetAtt:
          - CheckbillsScheduledLambda
          - Arn
        Id: CheckbillsScheduledLambda
  CheckbillsScheduledPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: CheckbillsScheduledLambda
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - CheckbillsScheduledEvent
        - Arn
  StaticBucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
        - ObjectOwnership: BucketOwnerEnforced
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
  StaticBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: StaticBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - s3:GetObject
          Effect: Allow
          Principal: '*'
          Resource:
          - Fn::Sub:
            - arn:aws:s3:::${bukkit}/*
            - bukkit:
                Ref: StaticBucket
          Sid: PublicReadGetObject
Outputs:
  API:
    Description: API Gateway (HTTP)
    Value:
      Fn::Sub:
      - https://${ApiId}.execute-api.${AWS::Region}.amazonaws.com
      - ApiId:
          Ref: HTTP
  ApiId:
    Description: API ID (ApiId)
    Value:
      Ref: HTTP
  PostbillEventTopic:
    Description: An SNS Topic
    Value:
      Ref: PostbillEventTopic
  TweetbillEventTopic:
    Description: An SNS Topic
    Value:
      Ref: TweetbillEventTopic
  BucketURL:
    Description: Bucket URL
    Value:
      Fn::Sub:
      - http://${bukkit}.s3-website.${AWS::Region}.amazonaws.com
      - bukkit:
          Ref: StaticBucket
